import type { Locale } from "@/types/resume";

export const translations = {
  en: { myCvs:"My CVs", create:"Create CV", templates:"Templates", features:"Features", saved:"Saved", saving:"Saving…", edit:"Edit", preview:"Preview", design:"Design", download:"Download PDF", personal:"Personal information", summary:"Professional summary", experience:"Work experience", education:"Education", skills:"Skills", languages:"Languages", projects:"Projects", certifications:"Certifications", courses:"Courses", awards:"Awards", interests:"Interests", references:"References", custom:"Custom section", add:"Add", delete:"Delete", duplicate:"Duplicate", print:"Print", sections:"Manage sections", ats:"ATS analysis", import:"Import JSON", export:"Export JSON", noCvs:"You haven't created a CV yet.", createFirst:"Create your first CV", privacy:"Your CV information is stored locally on this device.", aiUnavailable:"AI features require API configuration.", back:"Back", clear:"Clear example", hide:"Hide", show:"Show", name:"CV name", templateChanged:"Template changed", score:"CV score", guidance:"Guidance only — not a guarantee of passing a real ATS." },
  ro: { myCvs:"CV-urile mele", create:"Creează CV", templates:"Șabloane", features:"Funcții", saved:"Salvat", saving:"Se salvează…", edit:"Editează", preview:"Previzualizare", design:"Design", download:"Descarcă PDF", personal:"Informații personale", summary:"Rezumat profesional", experience:"Experiență profesională", education:"Educație", skills:"Competențe", languages:"Limbi", projects:"Proiecte", certifications:"Certificări", courses:"Cursuri", awards:"Premii", interests:"Interese", references:"Referințe", custom:"Secțiune personalizată", add:"Adaugă", delete:"Șterge", duplicate:"Duplică", print:"Tipărește", sections:"Organizează secțiunile", ats:"Analiză ATS", import:"Importă JSON", export:"Exportă JSON", noCvs:"Nu ai creat încă niciun CV.", createFirst:"Creează primul CV", privacy:"Datele CV-ului sunt stocate local pe acest dispozitiv.", aiUnavailable:"Funcțiile AI necesită configurarea unui API.", back:"Înapoi", clear:"Șterge exemplul", hide:"Ascunde", show:"Arată", name:"Nume CV", templateChanged:"Șablon schimbat", score:"Scor CV", guidance:"Doar orientativ — nu garantează trecerea unui sistem ATS." },
  hu: { myCvs:"Önéletrajzaim", create:"CV készítése", templates:"Sablonok", features:"Funkciók", saved:"Mentve", saving:"Mentés…", edit:"Szerkesztés", preview:"Előnézet", design:"Dizájn", download:"PDF letöltése", personal:"Személyes adatok", summary:"Szakmai összefoglaló", experience:"Szakmai tapasztalat", education:"Tanulmányok", skills:"Készségek", languages:"Nyelvek", projects:"Projektek", certifications:"Tanúsítványok", courses:"Kurzusok", awards:"Díjak", interests:"Érdeklődési kör", references:"Referenciák", custom:"Egyéni szakasz", add:"Hozzáadás", delete:"Törlés", duplicate:"Másolás", print:"Nyomtatás", sections:"Szakaszok kezelése", ats:"ATS elemzés", import:"JSON import", export:"JSON export", noCvs:"Még nem készítettél önéletrajzot.", createFirst:"Első CV elkészítése", privacy:"A CV adatai helyben, ezen az eszközön tárolódnak.", aiUnavailable:"Az AI funkciókhoz API-beállítás szükséges.", back:"Vissza", clear:"Példa törlése", hide:"Elrejtés", show:"Megjelenítés", name:"CV neve", templateChanged:"Sablon megváltoztatva", score:"CV pontszám", guidance:"Csak útmutatás — nem garantálja egy valódi ATS sikerét." }
} as const;
export const t = (locale: Locale) => translations[locale];
export const sectionLabels: Record<Locale, Record<string,string>> = {
  en:{summary:"Profile",experience:"Experience",education:"Education",skills:"Skills",languages:"Languages",projects:"Projects",certifications:"Certifications",courses:"Courses",awards:"Awards",interests:"Interests",references:"References"},
  ro:{summary:"Profil",experience:"Experiență profesională",education:"Educație",skills:"Competențe",languages:"Limbi",projects:"Proiecte",certifications:"Certificări",courses:"Cursuri",awards:"Premii",interests:"Interese",references:"Referințe"},
  hu:{summary:"Bemutatkozás",experience:"Szakmai tapasztalat",education:"Tanulmányok",skills:"Készségek",languages:"Nyelvek",projects:"Projektek",certifications:"Tanúsítványok",courses:"Kurzusok",awards:"Díjak",interests:"Érdeklődési kör",references:"Referenciák"}
};
